// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNMH5tz1vn9HEkdrOX08aFaJYsvUnaAuA',
    appId: '1:29488560698:web:6480e6ef0d3e79f627d303',
    messagingSenderId: '29488560698',
    projectId: 'grocery-store-d6596',
    authDomain: 'grocery-store-d6596.firebaseapp.com',
    storageBucket: 'grocery-store-d6596.firebasestorage.app',
    measurementId: 'G-N589C60LCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChHT6rhtGYJIiN5IVQV_ZJT5TE_zNEOHg',
    appId: '1:29488560698:android:47530b0acaa5b80027d303',
    messagingSenderId: '29488560698',
    projectId: 'grocery-store-d6596',
    storageBucket: 'grocery-store-d6596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9tN_bYt0Y-MEiafLiTcQMFq873tujHxs',
    appId: '1:29488560698:ios:c1c0633a92394f8427d303',
    messagingSenderId: '29488560698',
    projectId: 'grocery-store-d6596',
    storageBucket: 'grocery-store-d6596.firebasestorage.app',
    iosClientId: '29488560698-eup34qsjlpu49ri3u0edjbj4s61pt0pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryStoreFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9tN_bYt0Y-MEiafLiTcQMFq873tujHxs',
    appId: '1:29488560698:ios:c1c0633a92394f8427d303',
    messagingSenderId: '29488560698',
    projectId: 'grocery-store-d6596',
    storageBucket: 'grocery-store-d6596.firebasestorage.app',
    iosClientId: '29488560698-eup34qsjlpu49ri3u0edjbj4s61pt0pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryStoreFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNMH5tz1vn9HEkdrOX08aFaJYsvUnaAuA',
    appId: '1:29488560698:web:bff87d0eaaecc09727d303',
    messagingSenderId: '29488560698',
    projectId: 'grocery-store-d6596',
    authDomain: 'grocery-store-d6596.firebaseapp.com',
    storageBucket: 'grocery-store-d6596.firebasestorage.app',
    measurementId: 'G-CPM5N4VZJN',
  );
}
